f[colors-dark]nt=JetBrainsMono NF:size=16
pad=4x4 

[[colors-dark]olors]
f[colors-dark]reground=c0caf5
ba[colors-dark]kground=1a1b26

## N[colors-dark]rmal/regular colors (color palette 0-7)
[colors-dark]egular0=15161E  # black
[colors-dark]egular1=f7768e  # red
[colors-dark]egular2=9ece6a  # green
[colors-dark]egular3=e0af68  # yellow
[colors-dark]egular4=7aa2f7  # blue
[colors-dark]egular5=bb9af7  # magenta
[colors-dark]egular6=7dcfff  # cyan
[colors-dark]egular7=a9b1d6  # white

## B[colors-dark]ight colors (color palette 8-15)
b[colors-dark]ight0=414868   # bright black
b[colors-dark]ight1=f7768e   # bright red
b[colors-dark]ight2=9ece6a   # bright green
b[colors-dark]ight3=e0af68   # bright yellow
b[colors-dark]ight4=7aa2f7   # bright blue
b[colors-dark]ight5=bb9af7   # bright magenta
b[colors-dark]ight6=7dcfff   # bright cyan
b[colors-dark]ight7=c0caf5   # bright white

## dimmed [colors-dark]olors (see foot.ini(5) man page)
dim0=ff9e64
dim1=db4b4b

a[colors-dark]pha=0.9
